### ISSUE TITLE
NamedEntityRecognizer 사용 시 No such file or directory : ner_model.bin

### ISSUE THREAD

**Issue by shinminchul** [fingeredman/teanaps#2]
안녕하세요

NamedEntityRecognizer를 사용하려고 하였으나, 리포지토리 내 model 폴더를 보면 ner_model.bin 이라는 파일이 없습니다

![image](https://user-images.githubusercontent.com/8541174/115989066-68483580-a5f7-11eb-8261-30c767550258.png)

해당 파일은 원래 제공되지 않는 것인가요?

**Comment by fingeredman** [comment]
TEANAPS 개체명인식기의 모델 파일은 API Documentation의 [개체명인식기](https://github.com/fingeredman/teanaps/blob/master/document/user_guide/teanaps_user_guide-api_documentation-nlp.md#22-teanapsnlpnamedentityrecognizer) 메뉴에서 제공하고 있습니다.
링크에 연결된 페이지의 Notes 항목의 링크를 통해 다운로드 가능합니다.
