### ISSUE TITLE
일반 리눅스 환경에서의 설치 문의

### ISSUE THREAD

**Issue by ByungjunKim** [fingeredman/teanaps#4]
안녕하세요 지난번에 잘 수정해주셔서 연구에 큰 도움이 되고 있습니다.
정식으로 수업시간에 활용한다면 또 연락드리겠습니다.

제가 코랩이 아니라 일반 리눅스 서버환경에서 teanaps를 설치하려는데 mecab 설치하는 부분에서 에러가 갑니다.
content 폴더가 없다는 에러인데요(코랩에만 있는 폴더라 그런가봅니다.)

`make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
Traceback (most recent call last):
  File "teanaps_setup.py", line 163, in <module>
    os.chdir('/content')
FileNotFoundError: [Errno 2] No such file or directory: '/content'
`

설치 관련해서 /content 폴더가 아니라 다른 폴더(user 이름으로 된 루트 폴더?)로 바꾸면 해결이 가능할지요.

**Comment by fingeredman** [comment]
"teanaps_install.py" 파일은 Google Colab 환경에 맞춰져 있으므로 로컬 환경에서 그대로 실행하시면 오류가 발생합니다. 

```python
# Google Colab 환경에서의 설치 명령어
!git clone https://github.com/fingeredman/teanaps.git
!python "teanaps/teanaps_setup.py"
```

로컬환경(Windows, Mac, Linux)에 `TEANAPS`를 설치하는 경우, [Requirments](https://github.com/fingeredman/teanaps/blob/master/document/user_guide/teanaps_user_guide-install_teanaps.md#requirements)의 각 라이브러리를 링크 참조하여 직접 설치 후,
`git clone ~` 명령어로 라이브러리만 다운로드하여 활용해주세요.

```python
# Requirements의 각 라이브러리 모두 설치 후 실행
# Clone 후 별도 설치없이 Import 가능
!git clone https://github.com/fingeredman/teanaps.git
```

**Comment by ByungjunKim** [comment]
아 일반 로컬에서는 그냥 requirements만 설치하면 되는군요 튜토리얼 정독하지 못한 제 책임입니다.
친절한 답변 감사합니다.
