### ISSUE TITLE
draw_tfidf 결과 x축 문제

### ISSUE THREAD

**Issue by ByungjunKim** [fingeredman/teanaps#5]
안녕하세요 패키지 잘 쓰고 있습니다.
draw_tfidf 함수 테스트 중 x축 label이 빈도수 내림차순기준으로 적혀있어야하는데, get_word_list() 결과 순서 기준으로 적힌것을 확인했습니다.

즉 아래 x축에는 tf, tfidf 빈도수 기준으로 상위 단어가 적혀있지 않고, get_word_list() 기준으로 적혀있었습니다.
draw_tfidf 함수 코드를 보니 get_word_list()가 x축 label로 쓰는걸로 되어있더군요. 
한번 확인해주실 수 있겠습니까? 
![newplot](https://user-images.githubusercontent.com/7889473/134672088-d9b4fc9c-506d-4c5e-baf9-01cdd0094290.png)

calculation_tfidf 함수는 tfidf_count=100, tfidf_state=True로 학습했으며

아래 리스트로 학습했습니다.(일부만 첨부)

['學/VERB 時/NOUN 習/VERB 亦/ADV 說/VERB 有/VERB 朋/NOUN 遠/VERB 方/NOUN 來/VERB 亦/ADV 樂/VERB 人/NOUN 知/VERB 慍/VERB 亦/ADV 君子/NOUN',
 '為/VERB 人/NOUN 孝/VERB 弟/NOUN 好/VERB 犯/VERB 上/NOUN 鮮/VERB 好/VERB 犯/VERB 上/NOUN 好/VERB 作/VERB 亂/VERB 未/ADV 有/VERB 君子/NOUN 務/VERB 本/NOUN 本/NOUN 立/VERB 道/NOUN 生/NOUN 孝/VERB 弟/NOUN 為/VERB 仁/NOUN 本/NOUN',
 '巧/VERB 言/NOUN 令/NOUN 色/NOUN 鮮/VERB 仁/NOUN',
 '日/NOUN 省/VERB 身/NOUN 為/VERB 人/NOUN 謀/VERB 忠/VERB 朋/NOUN 友/NOUN 交/VERB 信/VERB 傳/NOUN 習/VERB',
 '道/NOUN 乘/NOUN 國/NOUN 敬/VERB 事/NOUN 信/VERB 節/VERB 用/VERB 愛/VERB 人/NOUN 使/VERB 民/NOUN 以/VERB 時/NOUN',
 '弟子/NOUN 入/VERB 則/ADV 孝/VERB 出/VERB 則/ADV 弟/NOUN 謹/VERB 信/VERB 汎/VERB 愛/VERB 眾/NOUN 親/VERB 仁/NOUN 行/VERB 有/VERB 餘/NOUN 力/NOUN 則/ADV 以/VERB 學/VERB 文/NOUN',
 '賢/VERB 賢/VERB 易/VERB 色/NOUN 事/VERB 父/NOUN 母/NOUN 竭/VERB 力/NOUN 事/VERB 君/NOUN 致/VERB 身/NOUN 朋/NOUN 友/NOUN 交/ADV 言/VERB 有/VERB 信/NOUN 雖/ADV 曰/VERB 未/ADV 學/VERB 必/ADV 謂/VERB 學/VERB',
 '君子/NOUN 重/VERB 則/ADV 威/VERB 學/NOUN 則/ADV 固/VERB 主/NOUN 忠/VERB 信/VERB 無/VERB 友/NOUN 如/VERB 過/NOUN 則/ADV 勿/ADV 憚/VERB 改/VERB',
 '慎/VERB 終/VERB 追/VERB 遠/VERB 民/NOUN 德/NOUN 歸/VERB 厚/VERB',
 '夫子/NOUN 至/VERB 邦/NOUN 必/ADV 聞/VERB 政/NOUN 求/VERB 抑/VERB 與/VERB',
 '夫子/NOUN 溫/VERB 良/VERB 恭/VERB 儉/VERB 讓/VERB 以/VERB 得/VERB 夫子/NOUN 求/VERB 諸/NOUN 異/VERB 人/NOUN 求/VERB',
 '父/NOUN 在/VERB 觀/VERB 志/NOUN 父/NOUN 沒/VERB 觀/VERB 行/NOUN 年/NOUN 無/VERB 改/VERB 父/NOUN 道/NOUN 謂/VERB 孝/NOUN',
 '禮/NOUN 用/NOUN 和/VERB 為/VERB 貴/NOUN 先/NOUN 王/NOUN 道/NOUN 斯/ADV 為/VERB 美/NOUN 小/VERB 大/VERB 由/VERB 有/VERB 行/VERB 知/VERB 和/VERB 和/VERB 以/VERB 禮/NOUN 節/VERB 亦/ADV 行/VERB',
 '信/PROPN 近/VERB 義/NOUN 言/NOUN 復/VERB 恭/VERB 近/VERB 禮/NOUN 遠/VERB 恥/VERB 辱/VERB 因/VERB 失/VERB 親/NOUN 亦/ADV 宗/VERB',
 '君子/NOUN 食/NOUN 無/VERB 求/VERB 飽/VERB 居/VERB 無/VERB 求/VERB 安/VERB 敏/VERB 事/NOUN 慎/VERB 言/NOUN 就/VERB 有/VERB 道/NOUN 正/VERB 謂/VERB 好/VERB 學/NOUN',
 '貧/VERB 無/VERB 諂/VERB 富/VERB 無/VERB 驕/VERB 如/VERB',
 '可/VERB 未/ADV 若/VERB 貧/VERB 樂/VERB 富/VERB 好/VERB 禮/NOUN',
 '詩/NOUN 云/VERB 如/VERB 切/VERB 如/VERB 磋/VERB 如/VERB 琢/VERB 如/VERB 磨/VERB 謂/VERB',
 '賜/VERB 始/VERB 與/VERB 言/NOUN 詩/NOUN 告/VERB 往/VERB 知/VERB 來/VERB',
 '患/VERB 人/NOUN 知/VERB 患/NOUN 知/VERB 人/NOUN',
 '為/VERB 政/NOUN 以/VERB 德/NOUN 譬/VERB 如/VERB 北/NOUN 辰/NOUN 居/VERB 所/NOUN 眾/VERB 星/NOUN 共/VERB',
 '詩/NOUN 言/NOUN 以/VERB 蔽/VERB 曰/VERB 思/VERB 無/VERB 邪/NOUN']

**Comment by fingeredman** [comment]
해당 현상 확인하여 수정하였습니다.
다시한번 확인 부탁드립니다.

**Comment by ByungjunKim** [comment]
네네 확인해보겠습니다.
아 그리고 wiki (https://github.com/fingeredman/teanaps/wiki/TEXT-ANALYSIS#teanaps-api-documentation)에서
get_word_network_graph 함수 코드 예제가 틀린듯합니다.
get_co_matrix_graph 함수 예제가 적혀있었습니다.

**Comment by ByungjunKim** [comment]
해결됐습니다. 감사합니다!

**Comment by fingeredman** [comment]
단어 네트워크 시각화를 위한 _[. get_word_network_graph()](https://github.com/fingeredman/teanaps/wiki/TEXT-ANALYSIS#34-teanapstext_analysiscowordcalculator)_ 함수 설명과 샘플코드가 수정되었습니다.
