### ISSUE TITLE
Colab에서 하던 작업을 Docker로 옮겨서 작업했더니 동시출현빈도 계산이 작동하지 않습니다

### ISSUE THREAD

**Issue by Outouniverse** [fingeredman/teanaps#6]
Colab 파이썬 버전업 이슈로 안내해주신 Docker로 데이터를 옮겨 작업하였습니다.

SNA가 목적으로 데이터셋 세팅까지는 무리없이 진행하였으나,
calculation_co_matrix 함수를 돌렸더니 오래 걸려야 할 함수가 1초만에 종료되고,

이후
edge_list = co.get_edge_list()[:20]
edge_list
의 결과가 []로 나타납니다.

해결할 방법에 대해 말씀주실 수 있을까요?

tokenized_sentence_list 값이 좀 크기는 하나, 
오히려 로딩이 계속 되는 것이 아니라 연산이 바로 종료되는 상태라
수정 방향을 알고 싶습니다.

필요하시면 코드 및 데이터는 개별적으로 보내드릴 수 있도록 하겠습니다.
확인 부탁드립니다.

**Comment by fingeredman** [comment]
안녕하세요.
분석하신 코드를 아래 메일주소로 보내주시면 내용 확인하여 회신드리겠습니다.
admin@teanaps.com

**Comment by Outouniverse** [comment]
확인 및 회신 감사드립니다.
덕분에 문제 수정 완료하였습니다.
